FROM ubuntu:24.04

ARG TARGET_ENVIRONMENT
ARG VERSION
ARG FILE_NAME

ENV SECURITY_PATH="/security/${TARGET_ENVIRONMENT}"

RUN mkdir -p $SECURITY_PATH

COPY $FILE_NAME $SECURITY_PATH

ENTRYPOINT ["tail", "-f", "/dev/null"]
